[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dash_df_plot"
version = "0.0.15"
description = "dash_df_plot"
readme = "README.md"
requires-python = ">=3.5"
license = {file = "LICENSE"}
authors = [
    {name = "Brent Kendrick", email = "brent.kendrick@fp-biopharma.com"}
]
dependencies = [
    "numpy>=2.1.1",
    "pandas>=2.2.2",
    "dash_daq>=0.5.0",
    "dash>=2.1.4",
    "dash-bootstrap-components>=1.0.0",
    "multiprocess>=0.70",
    "psutil>=5.8.0",
    "redis>=3.5.3",
    "celery>=5.2.1",
    "jsonpickle>=2.0.0",
    "netcdf4>=1.7.1.post2",
    "openpyxl",
    "pythonnet",
    "fpbiolib>=0.5.15"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry"
]

[tool.setuptools]
include-package-data = true  # Ensures package data is included
packages = ["dash_df_plot"]  # Explicitly list the package to include
# You can also list other packages here if needed

[tool.setuptools.package-data]
# Explicitly include pyproject.toml from the root directory
dash_df_plot = ["pyproject.toml"]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests"]